<?php
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_COMPANY_WARNING_TEXT1"] = "Você é um verdadeiro profissional! Agora você tem mais de #COUNT# empresas no seu Bitrix24. Observação: você só poderá pesquisar empresas nos planos comerciais quando o número de empresas exceder #LIMIT#.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_COMPANY_WARNING_TEXT2"] = "Pesquisar tantas empresas exigirá recursos consideráveis, portanto, apenas os filtros predefinidos podem ser usados no plano Free. #HELPDESK_LINK#";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_CONTACT_WARNING_TEXT1"] = "Você é um verdadeiro profissional! Agora você tem mais de #COUNT# contatos no seu Bitrix24. Observação: você só poderá pesquisar contatos nos planos comerciais quando o número de contatos exceder #LIMIT#.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_CONTACT_WARNING_TEXT2"] = "Pesquisar tantos contatos exigirá recursos consideráveis, portanto, apenas os filtros predefinidos podem ser usados no plano Free. #HELPDESK_LINK#";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_DEAL_WARNING_TEXT1"] = "Você é um verdadeiro profissional! Agora você tem mais de #COUNT# negócios no seu Bitrix24. Observação: você só poderá pesquisar negócios nos planos comerciais quando o número de negócios exceder #LIMIT#.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_DEAL_WARNING_TEXT2"] = "Pesquisar tantos negócios exigirá recursos consideráveis, portanto, apenas os filtros predefinidos podem ser usados no plano Free. #HELPDESK_LINK#";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_FILTER_COMPANY_CONTENT"] = "Limite de pesquisa de empresa (#LIMIT#) atingido. Estamos nos esforçando para melhorar a qualidade e o desempenho do serviço para atender à sua escala de negócios. A quantidade de dados aumenta à medida que sua empresa cresce: novas tarefas, negócios e outras entidades são criadas todos os dias.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_FILTER_CONTACT_CONTENT"] = "Limite de pesquisa de contato (#LIMIT#) atingido. Estamos nos esforçando para melhorar a qualidade e o desempenho do serviço para atender à sua escala de negócios. A quantidade de dados aumenta à medida que sua empresa cresce: novas tarefas, negócios e outras entidades são criadas todos os dias.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_FILTER_CONTENT2"] = "Quanto maior a escala da sua empresa, mais dados para pesquisa você cria. Escolha um plano que se adeque aos seus dados para pesquisar mais rapidamente. #HELPDESK_LINK#";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_FILTER_DEAL_CONTENT"] = "Limite de pesquisa de negócio (#LIMIT#) atingido. Estamos nos esforçando para melhorar a qualidade e o desempenho do serviço para atender à sua escala de negócios. A quantidade de dados aumenta à medida que sua empresa cresce: novas tarefas, negócios e outras entidades são criadas todos os dias.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_FILTER_INVOICE_CONTENT"] = "Limite de pesquisa de fatura (#LIMIT#) atingido. Estamos nos esforçando para melhorar a qualidade e o desempenho do serviço para atender à sua escala de negócios. A quantidade de dados aumenta à medida que sua empresa cresce: novas tarefas, negócios e outras entidades são criadas todos os dias.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_FILTER_LEAD_CONTENT"] = "Limite de pesquisa de lead (#LIMIT#) atingido. Estamos nos esforçando para melhorar a qualidade e o desempenho do serviço para atender à sua escala de negócios. A quantidade de dados aumenta à medida que sua empresa cresce: novas tarefas, negócios e outras entidades são criadas todos os dias.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_FILTER_ORDER_CONTENT"] = "Limite de pesquisa de pedido (#LIMIT#) atingido. Estamos nos esforçando para melhorar a qualidade e o desempenho do serviço para atender à sua escala de negócios. A quantidade de dados aumenta à medida que sua empresa cresce: novas tarefas, negócios e outras entidades são criadas todos os dias.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_FILTER_QUOTE_CONTENT"] = "Limite de pesquisa de cotação (#LIMIT#) atingido. Estamos nos esforçando para melhorar a qualidade e o desempenho do serviço para atender à sua escala de negócios. A quantidade de dados aumenta à medida que sua empresa cresce: novas tarefas, negócios e outras entidades são criadas todos os dias.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_FILTER_TITLE"] = "Limite máximo de pesquisa atingido";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_HELPDESK_LINK"] = "Informações";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_INVOICE_WARNING_TEXT1"] = "Você é um verdadeiro profissional! Agora você tem mais de #COUNT# faturas no seu Bitrix24. Observação: você só poderá pesquisar faturas nos planos comerciais quando o número de faturas exceder #LIMIT#.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_INVOICE_WARNING_TEXT2"] = "Pesquisar tantas faturas exigirá recursos consideráveis, portanto, apenas os filtros predefinidos podem ser usados no plano Free. #HELPDESK_LINK#";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_LEAD_WARNING_TEXT1"] = "Você é um verdadeiro profissional! Agora você tem mais de #COUNT# leads no seu Bitrix24. Observação: você só poderá pesquisar leads nos planos comerciais quando o número de leads exceder #LIMIT#.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_LEAD_WARNING_TEXT2"] = "Pesquisar tantos leads exigirá recursos consideráveis, portanto, apenas os filtros predefinidos podem ser usados no plano Free. #HELPDESK_LINK#";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_LIMIT_CONTENT"] = "
	<p>Estamos nos esforçando para melhorar a qualidade e o desempenho do serviço para atender à sua escala de negócios. A quantidade de dados aumenta à medida que sua empresa cresce: novas tarefas, negócios e outras entidades são criadas todos os dias.</p>
	<p>Quanto maior a escala da sua empresa, mais dados a pesquisar você cria. Escolha um plano que se adapte aos seus dados para pesquisar mais rapidamente.</p>
";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_ORDER_WARNING_TEXT1"] = "Você é um verdadeiro profissional! Agora você tem mais de #COUNT# pedidos no seu Bitrix24. Observação: você só poderá pesquisar pedidos nos planos comerciais quando o número de pedidos exceder #LIMIT#.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_ORDER_WARNING_TEXT2"] = "Pesquisar tantos pedidos exigirá recursos consideráveis, portanto, apenas os filtros predefinidos podem ser usados no plano Free. #HELPDESK_LINK#";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_QUOTE_WARNING_TEXT1"] = "Você é um verdadeiro profissional! Agora você tem mais de #COUNT# orçamentos no seu Bitrix24. Observação: você só poderá pesquisar orçamentos nos planos comerciais quando o número de orçamentos exceder #LIMIT#.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_QUOTE_WARNING_TEXT2"] = "Pesquisar tantos orçamentos exigirá recursos consideráveis, portanto, apenas os filtros predefinidos podem ser usados no plano Free. #HELPDESK_LINK#";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_TITLE"] = "Limite de itens (#LIMIT#) atingido";
