<?php
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_COMPANY_WARNING_TEXT1"] = "¡Usted es un verdadero profesional! Ahora tiene más de #COUNT# empresas en su Bitrix24. Tenga en cuenta que podrá buscar empresas solo en los planes comerciales cuando su número sea mayor que #LIMIT#.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_COMPANY_WARNING_TEXT2"] = "La búsqueda de tantas compañías requerirá recursos considerables, así que solo los filtros predeterminados pueden utilizarse en el plan gratuito. #HELPDESK_LINK#";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_CONTACT_WARNING_TEXT1"] = "¡Usted es un verdadero profesional! Ahora tiene más de #COUNT# contactos en su Bitrix24. Tenga en cuenta que podrá buscar contactos solo en los planes comerciales cuando su número sea mayor que #LIMIT#.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_CONTACT_WARNING_TEXT2"] = "La búsqueda de tantos contactos requerirá recursos considerables, así que solo los filtros predeterminados pueden utilizarse en el plan gratuito. #HELPDESK_LINK#";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_DEAL_WARNING_TEXT1"] = "¡Usted es un verdadero profesional! Ahora tiene más de #COUNT# negociaciones en su Bitrix24. Tenga en cuenta que podrá buscar negociaciones solo en los planes comerciales cuando su número sea mayor que #LIMIT#.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_DEAL_WARNING_TEXT2"] = "La búsqueda de tantas negociaciones requerirá recursos considerables, así que solo los filtros predeterminados pueden utilizarse en el plan gratuito. #HELPDESK_LINK#";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_FILTER_COMPANY_CONTENT"] = "Alcanzó el límite de búsqueda de empresas (#LIMIT#). Nos esforzamos por mejorar la calidad y el rendimiento del servicio para adaptarnos a la escala de su empresa. La cantidad de datos aumenta a medida que su empresa crece: cada día se crean nuevas tareas, negociaciones y otras entidades.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_FILTER_CONTACT_CONTENT"] = "Alcanzó el límite de búsqueda de contactos (#LIMIT#). Nos esforzamos por mejorar la calidad y el rendimiento del servicio para adaptarnos a la escala de su empresa. La cantidad de datos aumenta a medida que su empresa crece: cada día se crean nuevas tareas, negociaciones y otras entidades.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_FILTER_CONTENT2"] = "Entre mayor sea la escala de su empresa, más datos de búsqueda creará. Elija un plan que se adapte a sus datos para realizar búsquedas más rápidamente. #HELPDESK_LINK#";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_FILTER_DEAL_CONTENT"] = "Alcanzó el límite de búsqueda de negociaciones (#LIMIT#). Nos esforzamos por mejorar la calidad y el rendimiento del servicio para adaptarnos a la escala de su empresa. La cantidad de datos aumenta a medida que su empresa crece: cada día se crean nuevas tareas, negociaciones y otras entidades.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_FILTER_INVOICE_CONTENT"] = "Alcanzó el límite de búsqueda de facturas (#LIMIT#). Nos esforzamos por mejorar la calidad y el rendimiento del servicio para adaptarnos a la escala de su empresa. La cantidad de datos aumenta a medida que su empresa crece: cada día se crean nuevas tareas, negociaciones y otras entidades.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_FILTER_LEAD_CONTENT"] = "Alcanzó el límite de búsqueda de prospectos (#LIMIT#). Nos esforzamos por mejorar la calidad y el rendimiento del servicio para adaptarnos a la escala de su empresa. La cantidad de datos aumenta a medida que su empresa crece: cada día se crean nuevas tareas, negociaciones y otras entidades.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_FILTER_ORDER_CONTENT"] = "Alcanzó el límite de búsqueda de pedidos (#LIMIT#). Nos esforzamos por mejorar la calidad y el rendimiento del servicio para adaptarnos a la escala de su empresa. La cantidad de datos aumenta a medida que su empresa crece: cada día se crean nuevas tareas, negociaciones y otras entidades.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_FILTER_QUOTE_CONTENT"] = "Alcanzó el límite de búsqueda de cotizaciones (#LIMIT#). Nos esforzamos por mejorar la calidad y el rendimiento del servicio para adaptarnos a la escala de su empresa. La cantidad de datos aumenta a medida que su empresa crece: cada día se crean nuevas tareas, negociaciones y otras entidades.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_FILTER_TITLE"] = "Alcanzó el límite máximo de búsqueda";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_HELPDESK_LINK"] = "Detalles";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_INVOICE_WARNING_TEXT1"] = "¡Usted es un verdadero profesional! Ahora tiene más de #COUNT# facturas en su Bitrix24. Tenga en cuenta que podrá buscar facturas solo en los planes comerciales cuando su número sea mayor que #LIMIT#.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_INVOICE_WARNING_TEXT2"] = "La búsqueda de tantas facturas requerirá recursos considerables, así que solo los filtros predeterminados pueden utilizarse en el plan gratuito. #HELPDESK_LINK#";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_LEAD_WARNING_TEXT1"] = "¡Usted es un verdadero profesional! Ahora tiene más de #COUNT# prospectos en su Bitrix24. Tenga en cuenta que podrá buscar prospectos solo en los planes comerciales cuando su número sea mayor que #LIMIT#.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_LEAD_WARNING_TEXT2"] = "La búsqueda de tantos prospectos requerirá recursos considerables, así que solo los filtros predeterminados pueden utilizarse en el plan gratuito. #HELPDESK_LINK#";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_LIMIT_CONTENT"] = "
	<p>Nos esforzamos por mejorar la calidad y el rendimiento del servicio para que se adapte a su escala comercial. La cantidad de datos aumenta a medida que su empresa crece: cada día se crean nuevas tareas, negociaciones y otras entidades.</p>
	<p>Entre mayor sea la escala de su empresa, más búsqueda de datos creará. Elija un plan que se ajuste a sus datos para buscar más rápidamente.</p>
";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_ORDER_WARNING_TEXT1"] = "¡Usted es un verdadero profesional! Ahora tiene más de #COUNT# pedidos en su Bitrix24. Tenga en cuenta que podrá buscar pedidos solo en los planes comerciales cuando su número sea mayor que #LIMIT#.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_ORDER_WARNING_TEXT2"] = "La búsqueda de tantos pedidos requerirá recursos considerables, así que solo los filtros predeterminados pueden utilizarse en el plan gratuito. #HELPDESK_LINK#";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_QUOTE_WARNING_TEXT1"] = "¡Usted es un verdadero profesional! Ahora tiene más de #COUNT# cotizaciones en su Bitrix24. Tenga en cuenta que podrá buscar cotizaciones solo en los planes comerciales cuando su número sea mayor a #LIMIT#.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_QUOTE_WARNING_TEXT2"] = "La búsqueda de tantas cotizaciones requerirá recursos considerables, así que solo los filtros predeterminados pueden utilizarse en el plan gratuito. #HELPDESK_LINK#";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_TITLE"] = "Alcanzó el límite de elementos (#LIMIT#)";
