<?php
$MESS["TASKS_BP_DOCUMENT_ENTITY_NAME"] = "Flujo";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_BUSY_QUEUE_PLURAL_0"] = "El flujo [flowUrl]{flowName}[/flowUrl] ya tiene una tarea pendiente de {totalTasksInQueue}. Puede administrar la carga de trabajo abriendo el proyecto [groupUrl]{groupName}[/groupUrl].";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_BUSY_QUEUE_PLURAL_1"] = "El flujo [flowUrl]{flowName}[/flowUrl] ya tiene {totalTasksInQueue} tareas pendientes. Puede administrar la carga de trabajo abriendo el proyecto [groupUrl]{groupName}[/groupUrl].";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_BUSY_QUEUE_PLURAL_2"] = "El flujo [flowUrl]{flowName}[/flowUrl] ya tiene {totalTasksInQueue} tareas pendientes. Puede administrar la carga de trabajo abriendo el proyecto [groupUrl]{groupName}[/groupUrl].";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_BUSY_RESPONSIBLE_PLURAL_0"] = "El flujo [flowUrl]{flowName}[/flowUrl] ya tiene {totalTasksInProgress} tareas en progreso. Puede administrar la carga de trabajo abriendo el proyecto [groupUrl]{groupName}[/groupUrl].";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_BUSY_RESPONSIBLE_PLURAL_1"] = "El flujo [flowUrl]{flowName}[/flowUrl] ya tiene {totalTasksInProgress} tareas en progreso. Puede administrar la carga de trabajo abriendo el proyecto [groupUrl]{groupName}[/groupUrl].";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_BUSY_RESPONSIBLE_PLURAL_2"] = "El flujo [flowUrl]{flowName}[/flowUrl] ya tiene {totalTasksInProgress} tareas en progreso. Puede administrar la carga de trabajo abriendo el proyecto [groupUrl]{groupName}[/groupUrl].";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_EFFICIENCY_LOWER_MESSAGE"] = "Flujo: [flowUrl]{flowName}[/flowUrl]: La eficiencia cayó por debajo del {targetEfficiency}%. Es posible que deba revisar las fechas límite de la tarea.";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_FORCED_FLOW_MANUAL_DISTRIBUTOR_CHANGE_ABSENT"] = "El usuario responsable de la distribución de tareas en el flujo [flowUrl]{flowName}[/flowUrl] está ausente. Ahora todas las tareas se le asignaron. Utilice las [flowSettingsUrl]preferencias del flujo[/flowSettingsUrl] para cambiar el método de distribución de tareas.";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_FORCED_FLOW_MANUAL_DISTRIBUTOR_CHANGE_MESSAGE"] = "El usuario responsable de la distribución de tareas en el flujo [flowUrl]{flowName}[/flowUrl] fue despedido. Ahora todas las tareas se le asignaron. Utilice las [flowSettingsUrl]preferencias del flujo[/flowSettingsUrl] para cambiar el método de distribución de tareas.";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_FORCED_FLOW_SWITCH_TO_MANUAL_DISTRIBUTION_ABSENT_MESSAGE"] = "Flujo: [flowUrl]{flowName}[/flowUrl]: Ahora todas las tareas se le asignaron a usted porque todos los empleados en la fila están ausentes. Utilice las [flowSettingsUrl]preferencias del flujo[/flowSettingsUrl] para agregar más empleados.";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_FORCED_FLOW_SWITCH_TO_MANUAL_DISTRIBUTION_MESSAGE"] = "Flujo [flowUrl]{flowName}[/flowUrl]: Ahora todas las tareas se le asignaron porque ya no hay empleados disponibles en la fila. Utilice las [flowSettingsUrl]preferencias del flujo[/flowSettingsUrl] para agregar más empleados.";
