<?php
$MESS["TASKS_BP_DOCUMENT_ENTITY_NAME"] = "Przepływ";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_BUSY_QUEUE_PLURAL_0"] = "Przepływ [flowUrl]{flowName}[/flowUrl] ma już {totalTasksInQueue} zadanie oczekujące. Obciążeniem można zarządzać, otwierając projekt [groupUrl]{groupName}[/groupUrl].";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_BUSY_QUEUE_PLURAL_1"] = "Przepływ [flowUrl]{flowName}[/flowUrl] ma już {totalTasksInQueue} zadania oczekujące. Obciążeniem można zarządzać, otwierając projekt [groupUrl]{groupName}[/groupUrl].";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_BUSY_QUEUE_PLURAL_2"] = "Przepływ [flowUrl]{flowName}[/flowUrl] ma już {totalTasksInQueue} zadań oczekujących. Obciążeniem można zarządzać, otwierając projekt [groupUrl]{groupName}[/groupUrl].";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_BUSY_RESPONSIBLE_PLURAL_0"] = "Przepływ [flowUrl]{flowName}[/flowUrl] ma już {totalTasksInProgress} zadanie w toku. Obciążeniem można zarządzać, otwierając projekt [groupUrl]{groupName}[/groupUrl].";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_BUSY_RESPONSIBLE_PLURAL_1"] = "Przepływ [flowUrl]{flowName}[/flowUrl] ma już {totalTasksInProgress} zadania w toku. Obciążeniem można zarządzać, otwierając projekt [groupUrl]{groupName}[/groupUrl].";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_BUSY_RESPONSIBLE_PLURAL_2"] = "Przepływ [flowUrl]{flowName}[/flowUrl] ma już {totalTasksInProgress} zadań w toku. Obciążeniem można zarządzać, otwierając projekt [groupUrl]{groupName}[/groupUrl].";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_EFFICIENCY_LOWER_MESSAGE"] = "Przepływ: [flowUrl]{flowName}[/flowUrl]: wydajność spadła poniżej {targetEfficiency}%. Być może warto sprawdzić terminy zadań.";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_FORCED_FLOW_MANUAL_DISTRIBUTOR_CHANGE_ABSENT"] = "Użytkownik odpowiedzialny za przydzielanie zadań w przepływie [flowUrl]{flowName}[/flowUrl] jest nieobecny. Wszystkie zadania są teraz przypisane do Ciebie. Aby zmienić metodę przydziału zadań, użyj [flowSettingsUrl]preferencji przepływu[/flowSettingsUrl].";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_FORCED_FLOW_MANUAL_DISTRIBUTOR_CHANGE_MESSAGE"] = "Użytkownik odpowiedzialny za przydzielanie zadań w przepływie [flowUrl]{flowName}[/flowUrl] został odrzucony. Wszystkie zadania są teraz przypisane do Ciebie. Aby zmienić metodę przydziału zadań, użyj [flowSettingsUrl]preferencji przepływu[/flowSettingsUrl].";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_FORCED_FLOW_SWITCH_TO_MANUAL_DISTRIBUTION_ABSENT_MESSAGE"] = "Przepływ [flowUrl]{flowName}[/flowUrl]: wszystkie zadania są teraz przypisane do Ciebie, ponieważ wszyscy pracownicy w kolejce są nieobecni. Aby dodać więcej pracowników, użyj [flowSettingsUrl]preferencji przepływu[/flowSettingsUrl].";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_FORCED_FLOW_SWITCH_TO_MANUAL_DISTRIBUTION_MESSAGE"] = "Przepływ [flowUrl]{flowName}[/flowUrl]: wszystkie zadania są teraz przypisane do Ciebie, ponieważ w kolejce nie ma już dostępnych pracowników. Aby dodać więcej pracowników, użyj [flowSettingsUrl]preferencji przepływu[/flowSettingsUrl].";
