<?php
$MESS["TASKS_BP_DOCUMENT_ENTITY_NAME"] = "Flux";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_BUSY_QUEUE_PLURAL_0"] = "Le flux [flowUrl]{flowName}[/flowUrl] a déjà {totalTasksInQueue} tâche en attente. Vous pouvez gérer la charge de travail en ouvrant le projet [groupUrl]{groupName}[/groupUrl].";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_BUSY_QUEUE_PLURAL_1"] = "Le flux [flowUrl]{flowName}[/flowUrl] a déjà {totalTasksInQueue} tâches en attente. Vous pouvez gérer la charge de travail en ouvrant le projet [groupUrl]{groupName}[/groupUrl].";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_BUSY_QUEUE_PLURAL_2"] = "Le flux [flowUrl]{flowName}[/flowUrl] a déjà {totalTasksInQueue} tâches en attente. Vous pouvez gérer la charge de travail en ouvrant le projet [groupUrl]{groupName}[/groupUrl].";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_BUSY_RESPONSIBLE_PLURAL_0"] = "Le flux [flowUrl]{flowName}[/flowUrl] a déjà {totalTasksInProgress} tâche en cours. Vous pouvez gérer la charge de travail en ouvrant le projet [groupUrl]{groupName}[/groupUrl].";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_BUSY_RESPONSIBLE_PLURAL_1"] = "Le flux [flowUrl]{flowName}[/flowUrl] a déjà {totalTasksInProgress} tâches en cours. Vous pouvez gérer la charge de travail en ouvrant le projet [groupUrl]{groupName}[/groupUrl].";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_BUSY_RESPONSIBLE_PLURAL_2"] = "Le flux [flowUrl]{flowName}[/flowUrl] a déjà {totalTasksInProgress} tâches en cours. Vous pouvez gérer la charge de travail en ouvrant le projet [groupUrl]{groupName}[/groupUrl].";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_EFFICIENCY_LOWER_MESSAGE"] = "Flux : [flowUrl]{flowName}[/flowUrl] : l'efficacité a diminué en dessous de {targetEfficiency} %. Vous devrez peut-être revoir la date limite de la tâche.";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_FORCED_FLOW_MANUAL_DISTRIBUTOR_CHANGE_ABSENT"] = "L'utilisateur responsable de la distribution des tâches dans le flux [flowUrl]{flowName}[/flowUrl] est absent. Utilisez les [flowSettingsUrl]préférences du flux[/flowSettingsUrl] pour modifier la méthode de distribution des tâches.";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_FORCED_FLOW_MANUAL_DISTRIBUTOR_CHANGE_MESSAGE"] = "L'utilisateur responsable de la distribution des tâches dans le flux [flowUrl]{flowName}[/flowUrl] a été renvoyé. Utilisez les [flowSettingsUrl]préférences du flux[/flowSettingsUrl] pour modifier la méthode de distribution des tâches.";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_FORCED_FLOW_SWITCH_TO_MANUAL_DISTRIBUTION_ABSENT_MESSAGE"] = "Flux : [flowUrl]{flowName}[/flowUrl]: toutes les tâches vous sont maintenant attribuées, car tous les employés repris dans la file d'attente sont absents. Utilisez les [flowSettingsUrl]préférences du flux[/flowSettingsUrl] pour ajouter d'autres employés.";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_FORCED_FLOW_SWITCH_TO_MANUAL_DISTRIBUTION_MESSAGE"] = "Flux [flowUrl]{flowName}[/flowUrl] : toutes les tâches vous sont maintenant attribuées, car il n'y a plus aucun employé disponible dans la file d'attente. Utilisez les [flowSettingsUrl]préférences du flux[/flowSettingsUrl] pour ajouter plus d'employés.";
