<?php
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_COMPANY_WARNING_TEXT1"] = "Vous êtes un vrai pro ! Vous avez maintenant plus de #COUNT# entreprises dans votre Bitrix24. Attention : dès que le nombre d'entreprises dépassera #LIMIT#, vous ne pourrez en rechercher qu'avec les offres commerciales.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_COMPANY_WARNING_TEXT2"] = "Rechercher un si grand nombre d'entreprises nécessitera des ressources considérables, c'est pourquoi seuls les filtres prédéfinis peuvent être utilisés avec l'offre gratuite. #HELPDESK_LINK#";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_CONTACT_WARNING_TEXT1"] = "Vous êtes un vrai pro ! Vous avez maintenant plus de #COUNT# contacts dans votre Bitrix24. Attention : dès que le nombre de contacts dépassera #LIMIT#, vous ne pourrez en rechercher qu'avec les offres commerciales.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_CONTACT_WARNING_TEXT2"] = "Rechercher un si grand nombre de contacts nécessitera des ressources considérables, c'est pourquoi seuls les filtres prédéfinis peuvent être utilisés avec l'offre gratuite. #HELPDESK_LINK#";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_DEAL_WARNING_TEXT1"] = "Vous êtes un vrai pro ! Vous avez maintenant plus de #COUNT# transactions dans votre Bitrix24. Attention : dès que le nombre de transactions dépassera #LIMIT#, vous ne pourrez en rechercher qu'avec les offres commerciales.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_DEAL_WARNING_TEXT2"] = "Rechercher un si grand nombre de transactions nécessitera des ressources considérables, c'est pourquoi seuls les filtres prédéfinis peuvent être utilisés avec l'offre gratuite. #HELPDESK_LINK#";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_FILTER_COMPANY_CONTENT"] = "Limite de recherche de sociétés (#LIMIT#) atteinte. Nous nous efforçons d'améliorer la qualité et les performances du service pour l'adapter à votre échelle commerciale. La quantité de données augmente à mesure que votre entreprise se développe : de nouvelles tâches, offres et autres entités sont créées chaque jour.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_FILTER_CONTACT_CONTENT"] = "Limite de recherche de contacts (#LIMIT#) atteinte. Nous nous efforçons d'améliorer la qualité et les performances du service pour l'adapter à votre échelle commerciale. La quantité de données augmente à mesure que votre entreprise se développe : de nouvelles tâches, offres et autres entités sont créées chaque jour.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_FILTER_CONTENT2"] = "Plus votre entreprise est grande, plus vous créez de données à rechercher. Choisissez une offre qui correspond à vos données afin d'accélérer la recherche.  #HELPDESK_LINK#";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_FILTER_DEAL_CONTENT"] = "Limite de recherche de transactions (#LIMIT#) atteinte. Nous nous efforçons d'améliorer la qualité et les performances du service pour l'adapter à votre échelle commerciale. La quantité de données augmente à mesure que votre entreprise se développe : de nouvelles tâches, offres et autres entités sont créées chaque jour.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_FILTER_DYNAMIC_CONTENT"] = "Votre processus intelligent contient plus de #LIMIT# articles. Veuillez passer à un abonnement supérieur pour rechercher plus d'articles.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_FILTER_INVOICE_CONTENT"] = "Limite de recherche de factures (#LIMIT#) atteinte. Nous nous efforçons d'améliorer la qualité et les performances du service pour l'adapter à votre échelle commerciale. La quantité de données augmente à mesure que votre entreprise se développe : de nouvelles tâches, offres et autres entités sont créées chaque jour.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_FILTER_LEAD_CONTENT"] = "Limite de recherche de prospects (#LIMIT#) atteinte. Nous nous efforçons d'améliorer la qualité et les performances du service pour l'adapter à votre échelle commerciale. La quantité de données augmente à mesure que votre entreprise se développe : de nouvelles tâches, offres et autres entités sont créées chaque jour.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_FILTER_ORDER_CONTENT"] = "Limite de recherche de commandes (#LIMIT#) atteinte. Nous nous efforçons d'améliorer la qualité et les performances du service pour l'adapter à votre échelle commerciale. La quantité de données augmente à mesure que votre entreprise se développe : de nouvelles tâches, offres et autres entités sont créées chaque jour.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_FILTER_QUOTE_CONTENT"] = "Limite de recherche de devis (#LIMIT#) atteinte. Nous nous efforçons d'améliorer la qualité et les performances du service pour l'adapter à votre échelle commerciale. La quantité de données augmente à mesure que votre entreprise se développe : de nouvelles tâches, offres et autres entités sont créées chaque jour.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_FILTER_TITLE"] = "Limite de recherche maximale atteinte";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_HELPDESK_LINK"] = "Détails";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_INVOICE_WARNING_TEXT1"] = "Vous êtes un vrai pro ! Vous avez maintenant plus de #COUNT# factures dans votre Bitrix24. Attention : dès que le nombre de factures dépassera #LIMIT#, vous ne pourrez en rechercher qu'avec les offres commerciales.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_INVOICE_WARNING_TEXT2"] = "Rechercher un si grand nombre de factures nécessitera des ressources considérables, c'est pourquoi seuls les filtres prédéfinis peuvent être utilisés avec l'offre gratuite. #HELPDESK_LINK#";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_LEAD_WARNING_TEXT1"] = "Vous êtes un vrai pro ! Vous avez maintenant plus de #COUNT# prospects dans votre Bitrix24. Attention : dès que le nombre de prospects dépassera #LIMIT#, vous ne pourrez en rechercher qu'avec les offres commerciales.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_LEAD_WARNING_TEXT2"] = "Rechercher un si grand nombre de prospects nécessitera des ressources considérables, c'est pourquoi seuls les filtres prédéfinis peuvent être utilisés avec l'offre gratuite. #HELPDESK_LINK#";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_LIMIT_CONTENT"] = "
	<p>Nous nous efforçons d'améliorer la qualité et les performances du service pour l'adapter à votre échelle commerciale. La quantité de données augmente à mesure que votre entreprise se développe : de nouvelles tâches, offres et autres entités sont créées chaque jour.</p>
	<p>Plus votre entreprise est grande, plus vous créez de données à rechercher. Choisissez une offre qui correspond à vos données pour rechercher plus rapidement.</p>
";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_ORDER_WARNING_TEXT1"] = "Vous êtes un vrai pro ! Vous avez maintenant plus de #COUNT# commandes dans votre Bitrix24. Attention : dès que le nombre de commandes dépassera #LIMIT#, vous ne pourrez en rechercher qu'avec les offres commerciales.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_ORDER_WARNING_TEXT2"] = "Rechercher un si grand nombre de commandes nécessitera des ressources considérables, c'est pourquoi seuls les filtres prédéfinis peuvent être utilisés avec l'offre gratuite. #HELPDESK_LINK#";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_QUOTE_WARNING_TEXT1"] = "Vous êtes un vrai pro ! Vous avez maintenant plus de #COUNT# devis dans votre Bitrix24. Attention : dès que le nombre de devis dépassera #LIMIT#, vous ne pourrez en rechercher qu'avec les offres commerciales.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_QUOTE_WARNING_TEXT2"] = "Rechercher un si grand nombre de devis nécessitera des ressources considérables, c'est pourquoi seuls les filtres prédéfinis peuvent être utilisés avec l'offre gratuite. #HELPDESK_LINK#";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_TITLE"] = "Limite d'articles (#LIMIT#) atteinte";
