<?php
$MESS["TASKS_BP_DOCUMENT_ENTITY_NAME"] = "Flusso";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_BUSY_QUEUE_PLURAL_0"] = "Il flusso [flowUrl]{flowName}[/flowUrl] ha già {totalTasksInQueue} incarico in sospeso. Apri il progetto [groupUrl]{groupName}[/groupUrl] per gestire il carico di lavoro.";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_BUSY_QUEUE_PLURAL_1"] = "Il flusso [flowUrl]{flowName}[/flowUrl] ha già {totalTasksInQueue} incarichi in sospeso. Apri il progetto [groupUrl]{groupName}[/groupUrl] per gestire il carico di lavoro.";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_BUSY_QUEUE_PLURAL_2"] = "Il flusso [flowUrl]{flowName}[/flowUrl] ha già {totalTasksInQueue} incarichi in sospeso. Apri il progetto [groupUrl]{groupName}[/groupUrl] per gestire il carico di lavoro.";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_BUSY_RESPONSIBLE_PLURAL_0"] = "Il flusso [flowUrl]{flowName}[/flowUrl] ha già {totalTasksInProgress} incarico in corso. Apri il progetto [groupUrl]{groupName}[/groupUrl] per gestire il carico di lavoro.";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_BUSY_RESPONSIBLE_PLURAL_1"] = "Il flusso [flowUrl]{flowName}[/flowUrl] ha già {totalTasksInProgress} incarichi in corso. Apri il progetto [groupUrl]{groupName}[/groupUrl] per gestire il carico di lavoro.";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_BUSY_RESPONSIBLE_PLURAL_2"] = "Il flusso [flowUrl]{flowName}[/flowUrl] ha già {totalTasksInProgress} incarichi in corso. Apri il progetto [groupUrl]{groupName}[/groupUrl] per gestire il carico di lavoro.";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_EFFICIENCY_LOWER_MESSAGE"] = "Flusso [flowUrl]{flowName}[/flowUrl]: l'efficienza è scesa al di sotto del {targetEfficiency}%. Potrebbe essere necessario rivedere le scadenze degli incarichi.";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_FORCED_FLOW_MANUAL_DISTRIBUTOR_CHANGE_ABSENT"] = "L'utente responsabile della distribuzione degli incarichi nel flusso [flowUrl]{flowName}[/flowUrl] è assente. Tutti gli incarichi sono stati assegnati a te. Usa le [flowSettingsUrl]preferenze del flusso[/flowSettingsUrl] per modificare il metodo di distribuzione degli incarichi.";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_FORCED_FLOW_MANUAL_DISTRIBUTOR_CHANGE_MESSAGE"] = "L'utente responsabile della distribuzione degli incarichi nel flusso [flowUrl]{flowName}[/flowUrl] è stato rimosso. Tutti gli incarichi sono stati assegnati a te. Usa le [flowSettingsUrl]preferenze del flusso[/flowSettingsUrl] per modificare il metodo di distribuzione degli incarichi.";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_FORCED_FLOW_SWITCH_TO_MANUAL_DISTRIBUTION_ABSENT_MESSAGE"] = "Flusso [flowUrl]{flowName}[/flowUrl]: tutti gli incarichi sono stati assegnati a te perché tutti gli altri dipendenti della coda sono assenti. Usa le [flowSettingsUrl]preferenze del flusso[/flowSettingsUrl] per aggiungere altri dipendenti.";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_FORCED_FLOW_SWITCH_TO_MANUAL_DISTRIBUTION_MESSAGE"] = "Flusso [flowUrl]{flowName}[/flowUrl]: tutti gli incarichi sono stati assegnati a te perché non ci sono altri dipendenti disponibili nella coda. Usa le [flowSettingsUrl]preferenze del flusso[/flowSettingsUrl] per aggiungere altri dipendenti.";
