<?php
$MESS["TASKS_BP_DOCUMENT_ENTITY_NAME"] = "Fluxo";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_BUSY_QUEUE_PLURAL_0"] = "O fluxo [flowUrl]{flowName}[/flowUrl] já possui {totalTasksInQueue} tarefa pendente. Você pode gerenciar a carga de trabalho abrindo o projeto [groupUrl]{groupName}[/groupUrl].";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_BUSY_QUEUE_PLURAL_1"] = "O fluxo [flowUrl]{flowName}[/flowUrl] já possui {totalTasksInQueue} tarefas pendentes. Você pode gerenciar a carga de trabalho abrindo o projeto [groupUrl]{groupName}[/groupUrl].";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_BUSY_QUEUE_PLURAL_2"] = "O fluxo [flowUrl]{flowName}[/flowUrl] já possui {totalTasksInQueue} tarefas pendentes. Você pode gerenciar a carga de trabalho abrindo o projeto [groupUrl]{groupName}[/groupUrl].";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_BUSY_RESPONSIBLE_PLURAL_0"] = "O fluxo [flowUrl]{flowName}[/flowUrl] já possui {totalTasksInProgress} tarefa em andamento. Você pode gerenciar a carga de trabalho abrindo o projeto [groupUrl]{groupName}[/groupUrl].";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_BUSY_RESPONSIBLE_PLURAL_1"] = "O fluxo [flowUrl]{flowName}[/flowUrl] já possui {totalTasksInProgress} tarefas em andamento. Você pode gerenciar a carga de trabalho abrindo o projeto [groupUrl]{groupName}[/groupUrl].";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_BUSY_RESPONSIBLE_PLURAL_2"] = "O fluxo [flowUrl]{flowName}[/flowUrl] já possui {totalTasksInProgress} tarefas em andamento. Você pode gerenciar a carga de trabalho abrindo o projeto [groupUrl]{groupName}[/groupUrl].";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_EFFICIENCY_LOWER_MESSAGE"] = "Fluxo: [flowUrl]{flowName}[/flowUrl] : a eficiência caiu abaixo de {targetEfficiency}%. Você pode ter que rever os prazos da tarefa.";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_FORCED_FLOW_MANUAL_DISTRIBUTOR_CHANGE_ABSENT"] = "O usuário responsável pela distribuição de tarefas no fluxo [flowUrl]{flowName}[/flowUrl] está ausente. Todas as tarefas agora são atribuídas a você. Use as preferências [flowSettingsUrl]de fluxo[/flowSettingsUrl] para alterar o método de distribuição da tarefa.";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_FORCED_FLOW_MANUAL_DISTRIBUTOR_CHANGE_MESSAGE"] = "O usuário responsável pela distribuição de tarefas no fluxo [flowUrl]{flowName}[/flowUrl] foi dispensado. Todas as tarefas agora são atribuídas a você. Use as preferências [flowSettingsUrl]de fluxo[/flowSettingsUrl] para alterar o método de distribuição da tarefa.";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_FORCED_FLOW_SWITCH_TO_MANUAL_DISTRIBUTION_ABSENT_MESSAGE"] = "Fluxo: [flowUrl]{flowName}[/flowUrl]: todas as tarefas agora são atribuídas a você porque todos os colaboradores na fila estão ausentes. Use as [flowSettingsUrl]preferências de fluxo[/flowSettingsUrl] para adicionar mais colaboradores.";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_FORCED_FLOW_SWITCH_TO_MANUAL_DISTRIBUTION_MESSAGE"] = "Fluxo [flowUrl]{flowName}[/flowUrl]: todas as tarefas agora são atribuídas a você porque não há mais colaboradores disponíveis na fila. Use as [flowSettingsUrl]preferências de fluxo[/flowSettingsUrl] para adicionar mais colaboradores.";
