<?php
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_COMPANY_WARNING_TEXT1"] = "Sei un vero professionista! Ora hai più di #COUNT# aziende nel tuo Bitrix24. Nota bene: potrai cercare aziende solo sui piani commerciali quando il loro numero supera #LIMIT#.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_COMPANY_WARNING_TEXT2"] = "La ricerca di così tante aziende richiederà risorse considerevoli, quindi solo i filtri preimpostati possono essere utilizzati sul piano gratuito. #HELPDESK_LINK#";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_CONTACT_WARNING_TEXT1"] = "Sei un vero professionista! Ora hai più di #COUNT# contatti nel tuo Bitrix24. Nota bene: potrai cercare contatti solo sui piani commerciali quando il loro numero supera #LIMIT#.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_CONTACT_WARNING_TEXT2"] = "La ricerca di così tanti contatti richiederà risorse considerevoli, quindi solo i filtri preimpostati possono essere utilizzati sul piano gratuito. #HELPDESK_LINK#";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_DEAL_WARNING_TEXT1"] = "Sei un vero professionista! Ora hai più di #COUNT# affari nel tuo Bitrix24. Nota bene: potrai cercare affari solo sui piani commerciali quando il loro numero supera #LIMIT#.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_DEAL_WARNING_TEXT2"] = "La ricerca di così tanti affari richiederà risorse considerevoli, quindi solo i filtri preimpostati possono essere utilizzati sul piano gratuito. #HELPDESK_LINK#";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_FILTER_COMPANY_CONTENT"] = "Raggiunto limite di ricerca delle aziende (#LIMIT#). Ci stiamo adoperando per migliorare la qualità e le prestazioni del servizio adattandolo alle tue esigenze professionali. La quantità di dati aumenta man mano che la tua azienda cresce: ogni giorno vengono creati nuovi incarichi, affari e altre entità.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_FILTER_CONTACT_CONTENT"] = "Raggiunto limite di ricerca dei contatti (#LIMIT#). Ci stiamo adoperando per migliorare la qualità e le prestazioni del servizio adattandolo alle tue esigenze professionali. La quantità di dati aumenta man mano che la tua azienda cresce: ogni giorno vengono creati nuovi incarichi, affari e altre entità.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_FILTER_CONTENT2"] = "Maggiore è la portata della tua attività, più dati di ricerca verranno creati. Scegli un piano che si adatti ai tuoi dati per velocizzare la ricerca. #HELPDESK_LINK#";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_FILTER_DEAL_CONTENT"] = "Raggiunto limite di ricerca degli affari (#LIMIT#). Ci stiamo adoperando per migliorare la qualità e le prestazioni del servizio adattandolo alle tue esigenze professionali. La quantità di dati aumenta man mano che la tua azienda cresce: ogni giorno vengono creati nuovi incarichi, affari e altre entità.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_FILTER_INVOICE_CONTENT"] = "Raggiunto limite di ricerca delle fatture (#LIMIT#). Ci stiamo adoperando per migliorare la qualità e le prestazioni del servizio adattandolo alle tue esigenze professionali. La quantità di dati aumenta man mano che la tua azienda cresce: ogni giorno vengono creati nuovi incarichi, affari e altre entità.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_FILTER_LEAD_CONTENT"] = "Raggiunto limite di ricerca dei lead (#LIMIT#). Ci stiamo adoperando per migliorare la qualità e le prestazioni del servizio adattandolo alle tue esigenze professionali. La quantità di dati aumenta man mano che la tua azienda cresce: ogni giorno vengono creati nuovi incarichi, affari e altre entità.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_FILTER_ORDER_CONTENT"] = "Raggiunto limite di ricerca degli ordini (#LIMIT#). Ci stiamo adoperando per migliorare la qualità e le prestazioni del servizio adattandolo alle tue esigenze professionali. La quantità di dati aumenta man mano che la tua azienda cresce: ogni giorno vengono creati nuovi incarichi, affari e altre entità.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_FILTER_QUOTE_CONTENT"] = "Raggiunto limite di ricerca dei preventivi (#LIMIT#). Ci stiamo adoperando per migliorare la qualità e le prestazioni del servizio adattandolo alle tue esigenze professionali. La quantità di dati aumenta man mano che la tua azienda cresce: ogni giorno vengono creati nuovi incarichi, affari e altre entità.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_FILTER_TITLE"] = "Limite massimo di ricerca raggiunto";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_HELPDESK_LINK"] = "Dettagli";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_INVOICE_WARNING_TEXT1"] = "Sei un vero professionista! Ora hai più di #COUNT# fatture nel tuo Bitrix24. Nota bene: potrai cercare fatture solo sui piani commerciali quando il loro numero supera #LIMIT#.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_INVOICE_WARNING_TEXT2"] = "La ricerca di così tante fatture richiederà risorse considerevoli, quindi solo i filtri preimpostati possono essere utilizzati sul piano gratuito. #HELPDESK_LINK#";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_LEAD_WARNING_TEXT1"] = "Sei un vero professionista! Ora hai più di #COUNT# lead nel tuo Bitrix24. Nota bene: potrai cercare lead solo sui piani commerciali quando il loro numero supera #LIMIT#.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_LEAD_WARNING_TEXT2"] = "La ricerca di così tanti lead richiederà risorse considerevoli, quindi solo i filtri preimpostati possono essere utilizzati sul piano gratuito. #HELPDESK_LINK#";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_LIMIT_CONTENT"] = "
	<p>Ci stiamo adoperando per migliorare la qualità e le prestazioni del servizio adattandolo alle tue esigenze professionali. La quantità di dati aumenta man mano che la tua azienda cresce: ogni giorno vengono creati nuovi incarichi, affari e altre entità.</p>
	<p>Maggiori sono le dimensioni della tua attività, maggiore è il numero di dati creati che puoi cercare. Scegli un piano adatto ai tuoi dati per effettuare ricerche più rapidamente.</p>
";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_ORDER_WARNING_TEXT1"] = "Sei un vero professionista! Ora hai più di #COUNT# ordini nel tuo Bitrix24. Nota bene: potrai cercare ordini solo sui piani commerciali quando il loro numero supera #LIMIT#.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_ORDER_WARNING_TEXT2"] = "La ricerca di così tanti ordini richiederà risorse considerevoli, quindi solo i filtri preimpostati possono essere utilizzati sul piano gratuito. #HELPDESK_LINK#";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_QUOTE_WARNING_TEXT1"] = "Sei un vero professionista! Ora hai più di #COUNT# preventivi nel tuo Bitrix24. Nota bene: potrai cercare preventivi solo sui piani commerciali quando il loro numero supera #LIMIT#.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_QUOTE_WARNING_TEXT2"] = "La ricerca di così tanti preventivi richiederà risorse considerevoli, quindi solo i filtri preimpostati possono essere utilizzati sul piano gratuito. #HELPDESK_LINK#";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_TITLE"] = "Limite elementi (#LIMIT#) raggiunto";
