<?php
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_COMPANY_WARNING_TEXT1"] = "Jesteś prawdziwym profesjonalistą! Aktualnie masz więcej niż #COUNT# firm w swoim Bitrix24. Uwaga: po przekroczeniu limitu #LIMIT#, firmy można wyszukiwać wyłącznie w planach płatnych.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_COMPANY_WARNING_TEXT2"] = "Przeszukiwanie tak wielu firm wymaga znacznych zasobów, dlatego w planie bezpłatnym można używać wyłącznie wstępnie ustawionych filtrów. #HELPDESK_LINK#";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_CONTACT_WARNING_TEXT1"] = "Jesteś prawdziwym profesjonalistą! Aktualnie masz więcej niż #COUNT# kontaktów w swoim Bitrix24. Uwaga: po przekroczeniu limitu #LIMIT#, kontakty można wyszukiwać wyłącznie w planach płatnych.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_CONTACT_WARNING_TEXT2"] = "Przeszukiwanie tak wielu kontaktów wymaga znacznych zasobów, dlatego w planie bezpłatnym można używać wyłącznie wstępnie ustawionych filtrów. #HELPDESK_LINK#";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_DEAL_WARNING_TEXT1"] = "Jesteś prawdziwym profesjonalistą! Aktualnie masz więcej niż #COUNT# dealów w swoim Bitrix24. Uwaga: po przekroczeniu limitu #LIMIT#, deale można wyszukiwać wyłącznie w planach płatnych.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_DEAL_WARNING_TEXT2"] = "Przeszukiwanie tak wielu dealów wymaga znacznych zasobów, dlatego w planie bezpłatnym można używać wyłącznie wstępnie ustawionych filtrów. #HELPDESK_LINK#";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_FILTER_COMPANY_CONTENT"] = "Limit wyszukiwania firm (#LIMIT#). Staramy się poprawiać jakość usług i wydajność, aby pasowały do wielkości danej firmy. Ilość danych rośnie wraz z rozwojem biznesu: każdego dnia tworzone są nowe zadania, deale i inne obiekty.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_FILTER_CONTACT_CONTENT"] = "Limit wyszukiwania kontaktów (#LIMIT#). Staramy się poprawiać jakość usług i wydajność, aby pasowały do wielkości danej firmy. Ilość danych rośnie wraz z rozwojem biznesu: każdego dnia tworzone są nowe zadania, deale i inne obiekty.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_FILTER_CONTENT2"] = "Im większa firma, tym więcej danych do przeszukiwania. Wybierz plan, który pasuje do Twoich danych, aby szybciej wyszukiwać.  #HELPDESK_LINK#";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_FILTER_DEAL_CONTENT"] = "Limit wyszukiwania dealów (#LIMIT#). Staramy się poprawiać jakość usług i wydajność, aby pasowały do wielkości danej firmy. Ilość danych rośnie wraz z rozwojem biznesu: każdego dnia tworzone są nowe zadania, deale i inne obiekty.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_FILTER_INVOICE_CONTENT"] = "Limit wyszukiwania faktur (#LIMIT#). Staramy się poprawiać jakość usług i wydajność, aby pasowały do wielkości danej firmy. Ilość danych rośnie wraz z rozwojem biznesu: każdego dnia tworzone są nowe zadania, deale i inne obiekty.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_FILTER_LEAD_CONTENT"] = "Limit wyszukiwania leadów (#LIMIT#). Staramy się poprawiać jakość usług i wydajność, aby pasowały do wielkości danej firmy. Ilość danych rośnie wraz z rozwojem biznesu: każdego dnia tworzone są nowe zadania, deale i inne obiekty.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_FILTER_ORDER_CONTENT"] = "Limit wyszukiwania zamówień (#LIMIT#). Staramy się poprawiać jakość usług i wydajność, aby pasowały do wielkości danej firmy. Ilość danych rośnie wraz z rozwojem biznesu: każdego dnia tworzone są nowe zadania, deale i inne obiekty.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_FILTER_QUOTE_CONTENT"] = "Limit wyszukiwania ofert (#LIMIT#). Staramy się poprawiać jakość usług i wydajność, aby pasowały do wielkości danej firmy. Ilość danych rośnie wraz z rozwojem biznesu: każdego dnia tworzone są nowe zadania, deale i inne obiekty.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_FILTER_TITLE"] = "Osiągnięto maksymalny limit wyszukiwania";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_HELPDESK_LINK"] = "Szczegóły";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_INVOICE_WARNING_TEXT1"] = "Jesteś prawdziwym profesjonalistą! Aktualnie masz więcej niż #COUNT# faktur w swoim Bitrix24. Uwaga: po przekroczeniu limitu #LIMIT#, faktury można wyszukiwać wyłącznie w planach płatnych.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_INVOICE_WARNING_TEXT2"] = "Przeszukiwanie tak wielu faktur wymaga znacznych zasobów, dlatego w planie bezpłatnym można używać wyłącznie wstępnie ustawionych filtrów. #HELPDESK_LINK#";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_LEAD_WARNING_TEXT1"] = "Jesteś prawdziwym profesjonalistą! Aktualnie masz więcej niż #COUNT# leadów w swoim Bitrix24. Uwaga: po przekroczeniu limitu #LIMIT#, leadów można wyszukiwać wyłącznie w planach płatnych.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_LEAD_WARNING_TEXT2"] = "Przeszukiwanie tak wielu leadów wymaga znacznych zasobów, dlatego w planie bezpłatnym można używać wyłącznie wstępnie ustawionych filtrów. #HELPDESK_LINK#";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_LIMIT_CONTENT"] = "
	<p>Staramy się poprawiać jakość usług i wydajność, aby pasowały do wielkości danej firmy. Ilość danych rośnie wraz z rozwojem biznesu: każdego dnia tworzone są nowe zadania, deale i inne obiekty.</p>
	<p>Im większa firma, tym więcej danych do przeszukiwania. Wybierz plan, który pasuje do Twoich danych, aby szybciej wyszukiwać.</p>
";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_ORDER_WARNING_TEXT1"] = "Jesteś prawdziwym profesjonalistą! Aktualnie masz więcej niż #COUNT# zamówień w swoim Bitrix24. Uwaga: po przekroczeniu limitu #LIMIT#, zamówienia można wyszukiwać wyłącznie w planach płatnych.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_ORDER_WARNING_TEXT2"] = "Przeszukiwanie tak wielu zamówień wymaga znacznych zasobów, dlatego w planie bezpłatnym można używać wyłącznie wstępnie ustawionych filtrów. #HELPDESK_LINK#";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_QUOTE_WARNING_TEXT1"] = "Jesteś prawdziwym profesjonalistą! Aktualnie masz więcej niż #COUNT# ofert w swoim Bitrix24. Uwaga: po przekroczeniu limitu #LIMIT#, oferty można wyszukiwać wyłącznie w planach płatnych.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_QUOTE_WARNING_TEXT2"] = "Przeszukiwanie tak wielu ofert wymaga znacznych zasobów, dlatego w planie bezpłatnym można używać wyłącznie wstępnie ustawionych filtrów. #HELPDESK_LINK#";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_TITLE"] = "Osiągnięto limit (#LIMIT#) elementów";
